version: '3'

services:
  django:
    build: ./rentAccess
    container_name: django_sb
    ports:
      - '10.0.0.2:8000:8000'
    env_file:
      - ./rentAccess/.env
    command: gunicorn rentAccess.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./rentAccess/:/usr/src/app/
  celery:
    container_name: cl01
    build: ./rentAccess
    command: celery -A rentAccess worker -l info --purge
    env_file:
      - ./rentAccess/.env
    volumes:
      - ./rentAccess/:/usr/src/app/
  celery-beat:
    build: ./rentAccess
    command: celery -A rentAccess beat -l info
    env_file:
      - ./rentAccess/.env
    volumes:
      - ./rentAccess/:/usr/src/app/
