version: '3'

services:
  django:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    command: gunicorn rentAccess.wsgi:application --bind 0.0.0.0:8000
  celery:
      build: .
      command: celery -A rentAccess worker -l info
  celery-beat:
    build: .
    command: celery -A rentAccess beat -l info