version: '3'

services:
  django:
    build: .
    container_name: django_sb
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: gunicorn rentAccess.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - ./rentAccess:.
  celery:
    container_name: cl01
    build: .
    command: celery -A rentAccess worker -l info --purge
    volumes:
      - ./rentAccess:.
  celery-beat:
    build: .
    command: celery -A rentAccess beat -l info
    volumes:
      - ./rentAccess:.
