# Generated by Django 3.1.2 on 2021-01-28 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_delete_bookings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_from', models.DateTimeField()),
                ('booked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('number_of_clients', models.IntegerField(blank=True, default=1)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Approved'), ('AWAITING', 'Awaiting action from the owner'), ('DECLINED', 'The owner declined the request')], default='AWAITING', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('booked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_property', to='properties.property')),
            ],
        ),
    ]
