# Generated by Django 3.1.2 on 2021-01-26 07:06

from django.db import migrations, models
import django.db.models.deletion
import register.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('hash_id', models.CharField(max_length=256, unique=True, verbose_name='hash_id')),
                ('description', models.TextField(blank=True, default='', max_length=200, verbose_name='description')),
                ('is_on', models.BooleanField(default=True, verbose_name='is_on')),
                ('is_approved', models.BooleanField(default=True, verbose_name='is_approved')),
                ('last_echo', models.DateTimeField(auto_now_add=True, verbose_name='last_echo')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.PositiveIntegerField(default=None, editable=False, validators=[register.validators.key_validator], verbose_name='code')),
                ('hash_code', models.CharField(max_length=256, unique=True, verbose_name='hash_code')),
                ('access_start', models.DateTimeField(verbose_name='access_start')),
                ('access_stop', models.DateTimeField(verbose_name='access_stop')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_code', to='register.lock', verbose_name='lock_id')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('card_id', models.CharField(max_length=9, unique=True, validators=[register.validators.card_validator], verbose_name='card')),
                ('hash_id', models.CharField(max_length=256, unique=True, verbose_name='hash_id')),
                ('is_master', models.BooleanField(default=False, verbose_name='is_master')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_key', to='register.lock', verbose_name='lock_id')),
            ],
        ),
    ]
