# Generated by Django 3.1.2 on 2021-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('acc_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActionTypes',
            fields=[
                ('act_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionLevels',
            fields=[
                ('p_level', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultTypes',
            fields=[
                ('res_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
