# Generated by Django 3.1.2 on 2021-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.IntegerField(default=0, verbose_name='lock_id')),
                ('hash_code', models.CharField(max_length=256, verbose_name='hash_code')),
                ('try_time', models.DateTimeField(verbose_name='try_time')),
                ('result', models.BooleanField(verbose_name='result')),
                ('is_failed', models.BooleanField(default=False, verbose_name='is_failed')),
            ],
            options={
                'db_table': 'Logs',
                'ordering': ['-try_time'],
            },
        ),
    ]
