<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-07 14:10
=======
# Generated by Django 3.1.2 on 2020-10-27 20:07
>>>>>>> backend-profile

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
=======
        ('userAccount', '0001_initial'),
>>>>>>> backend-profile
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
<<<<<<< HEAD
                ('price', models.CharField(max_length=100)),
                ('available', models.BinaryField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('price', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('image', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAccount.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('POST', 'Post Request'), ('PUT', 'PUT Request'), ('PATCH', 'PATCH Request'), ('DELETE', 'DELETE Request'), ('DEACTIVATE', 'DEACTIVATE property'), ('GIVE_ACC', 'Give access to property')], max_length=300)),
                ('act_time', models.DateTimeField(verbose_name='act_time')),
                ('result', models.BooleanField(verbose_name='result')),
                ('listed_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> backend-profile
            ],
        ),
    ]
