# Generated by Django 3.1.2 on 2020-10-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20201007_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userpics/'),
        ),
    ]
