# Generated by Django 3.1.2 on 2020-10-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20201008_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='author_id',
            new_name='author',
        ),
    ]
