<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-07 23:10
=======
# Generated by Django 3.1.2 on 2020-10-27 20:07
>>>>>>> backend-profile

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('userpic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('about_me', models.TextField(blank=True)),
=======
                ('account_type', models.CharField(choices=[('ADMIN', 'Admin User'), ('STAFF', 'Staff User'), ('OWNER', 'Owner User'), ('CLIENT', 'Client User'), ('OTHER', 'Other User')], max_length=300)),
>>>>>>> backend-profile
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
