# Generated by Django 3.1.2 on 2020-10-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('ADMIN', 'Admin User'), ('STAFF', 'Staff User'), ('OWNER', 'Owner User'), ('CLIENT', 'Client User'), ('OTHER', 'Other User')], default='OWNER', max_length=300),
        ),
    ]
