# Generated by Django 3.1.2 on 2020-10-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_auto_20201008_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.BooleanField(default=True),
        ),
    ]
