# Generated by Django 3.1.2 on 2020-10-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_auto_20201008_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
