# Generated by Django 3.1.2 on 2020-10-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_auto_20201008_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
