# Generated by Django 3.1.2 on 2020-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0010_auto_20201008_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
