# Generated by Django 3.1.2 on 2020-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0014_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
