# Generated by Django 3.1.2 on 2020-10-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0016_auto_20201008_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pat_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sec_name',
        ),
    ]
